/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kr_ac_sch_se_algorithm_bandpassfilter */

#ifndef _Included_kr_ac_sch_se_algorithm_bandpassfilter
#define _Included_kr_ac_sch_se_algorithm_bandpassfilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kr_ac_sch_se_algorithm_bandpassfilter
 * Method:    printTest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_kr_ac_sch_se_algorithm_bandpassfilter_printTest
  (JNIEnv *env, jclass thiz);

/*
 * Class:     kr_ac_sch_se_algorithm_bandpassfilter
 * Method:    calculation
 * Signature: ([D[D[DI)[D
 *
 */
JNIEXPORT jdoubleArray JNICALL Java_kr_ac_sch_se_algorithm_bandpassfilter_calculation
  (JNIEnv *env, jclass thiz, jdoubleArray b, jdoubleArray a, jdoubleArray signal, jint signal_length);

#ifdef __cplusplus
}
#endif
#endif
